sonar.projectKey=everybodydaniel_Toernberechnung-iOS
sonar.organization=everybodydaniel
sonar.projectName=Toernberechnung iOS
sonar.projectVersion=1.0.0

sonar.sources=Toernberechnung
sonar.tests=ToernberechnungTests
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.xcodeproj/**,**/DerivedData/**,**/.build/**,**/Package.resolved
sonar.test.inclusions=ToernberechnungTests/**/*.swift
sonar.swift.swiftLint.reportPaths=reports/swiftlint.json
